### PR TITLE
Add cluster data source, tidy Makefile

### PR DESCRIPTION
**Pull request by fhke**

### CODE REVIEW

**Comment by thecodeassassin** [comment]
Hi @fhke , before we can merge this PR and make a new release. Could you please update your fork to the latest commit on main? It contains some breaking changes.

See: https://github.com/symbiosis-cloud/symbiosis-go/releases/tag/v1.0.12

**Comment by thecodeassassin** [comment]
@fhke small reminder. Have you seen my earlier message ? We would like to have this PR merged soon. Thanks!

**Comment by fhke** [comment]
Hi @thecodeassassin, apologies for the delayed response. I've rebased from main, could you review please?

**Comment by thecodeassassin** [comment]
> Hi @thecodeassassin, apologies for the delayed response. I've rebased from main, could you review please?

LGTM

**Pull request merged**
