### PR TITLE
fix: remove hardcoded os+arch variable in makefile

### LINKED ISSUE #17: Dev: Architecture is hardcoded
https://github.com/symbiosis-cloud/terraform-provider-symbiosis/blob/7ba6a712aba45e34e3486a8b4d6342a8c4950aa7/Makefile#L7

In the Makefile, the architecture is hardcoded to the Mac kernel, which needs manual adaption for running `make install` on other OSs. Since I can't find an easy fix for automatic detection, I'd recommend to write a few words into the README.

### PR DESCRIPTION
**Pull request by Styren**
Resolves #17

### CODE REVIEW

**Comment by Styren** [comment]
Current dependencies on/for this PR:
* main
  * **PR #18** <a href="https://app.graphite.dev/github/pr/symbiosis-cloud/terraform-provider-symbiosis/18" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/symbiosis-cloud/terraform-provider-symbiosis/18?utm_source=stack-comment).

**Comment by HerHde** [comment]
Example of execution on my machine (Arch based):

```shell
$ make install
go build -o terraform-provider-symbiosis
make: arch: No such file or directory
make: arch: No such file or directory
mkdir -p ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_
mv terraform-provider-symbiosis ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_
```

Well, `arch` is not installed by default on my machine. Running it on Debian-based systems, however, it returns `x86_64`, which is still not the desired `amd64`, right? This was the tricky part I meant.

Maybe we can default on error and for `x86_64` to `amd64`, or would that be ignorant?

I'd also like to mention a few trailing spaces from line 40 onwards ;-)

**Comment by Styren** [comment]
> Example of execution on my machine (Arch based):
> 
> ```shell
> $ make install
> go build -o terraform-provider-symbiosis
> make: arch: No such file or directory
> make: arch: No such file or directory
> mkdir -p ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_
> mv terraform-provider-symbiosis ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_
> ```
> 
> Well, `arch` is not installed by default on my machine. Running it on Debian-based systems, however, it returns `x86_64`, which is still not the desired `amd64`, right? This was the tricky part I meant.
> 
> Maybe we can default on error and for `x86_64` to `amd64`, or would that be ignorant?
> 
> I'd also like to mention a few trailing spaces from line 40 onwards ;-)

Yep that was perhaps a bit too ambitious haha... I found how they did it in the kubernetes plugin:
```make
OS_ARCH   ?= $(shell go env GOOS)_$(shell go env GOARCH)
```
Could you check if it works for you this time?

(thanks for highlighting the trailing whitespace)

**Comment by HerHde** [comment]
```shell
$ make install
go build -o terraform-provider-symbiosis
mkdir -p ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_amd64
mv terraform-provider-symbiosis ~/.terraform.d/plugins/symbiosis.host/symbiosis/symbiosis/0.3/linux_amd64
```

Works on my machine :+1:

**Review by HerHde — APPROVED** [review]

**Pull request merged**
